spring:
  application:
    name: AIGOU-EUREKA
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #是否注册到Eureka注册列表中
    fetchRegistry: false #是否拉取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机配置