server:
  port: 9527
spring:
  application:
    name: YOUGOU-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #注册到eureka
  instance:
    instance-id: yougou-zuul-gateway-9527.com #为当前服务器添加实例的标识
    prefer-ip-address: true
zuul:
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:
    plat:
      path: /plat/**
      service-id: yougou-plat