server:
  port: 1299
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: yougou-config-server:1299.com
    prefer-ip-address: true
spring:
  #profiles:
    #active: native #读取本地配置
  application:
    name: YOUGOU-CONFIG-SERVER
  cloud:
    config:
      server:
        #native:
          #search-locations: E:/program/github/aigou-config #本地配置所在的目录
        git:
          uri: https://github.com/chenzhongfang1121/yougou-config.git
          username: chenzhongfang1121
          password: 1121chenzhongfang.